language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1 PHP_LATEST_STABLE=7.1
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1
    dist: precise

before_install:
  - npm i npm@latest -g
  - echo $TRAVIS_PHP_VERSION
  - chmod +x docker-compose.yml
  - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]; then docker-compose up -d; fi
  - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]; then sudo chmod 777 -R ~/wordpress_data/; fi

before_script:
  - phpenv config-rm xdebug.ini
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh give_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - phpunit -c phpunit.xml
  - |
    if [ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]; then
      until $(curl --output /dev/null --silent --head --fail http://localhost:8004); do printf '.'; sleep 5; done;
      cd ~/wordpress_data/wp-content/plugins
      git clone -b $TRAVIS_BRANCH --single-branch https://github.com/WordImpress/Give.git
      cd ~/wordpress_data/wp-content/plugins/Give/
      docker exec give_wordpress_1 wp plugin activate Give
      composer install
      npm install
      npm run dev
      npm run test
    fi

after_script:
  - bash tests/bin/travis.sh after