language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1 PHP_LATEST_STABLE=7.1
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1
    dist: precise

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]] && [[ ${TRAVIS_BRANCH} == "master" ]]; then npm i npm@latest -g fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]] && [[ ${TRAVIS_BRANCH} == "master" ]]; then chmod +x docker-compose.yml fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]] && [[ ${TRAVIS_BRANCH} == "master" ]]; then docker-compose up -d; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]] && [[ ${TRAVIS_BRANCH} == "master" ]]; then sudo chmod 777 -R ~/wordpress_data/; fi

before_script:
  - phpenv config-rm xdebug.ini
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh give_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - phpunit -c phpunit.xml
  - bash tests/e2e/bin/install.sh

after_script:
  - bash tests/bin/travis.sh after
