# This is a basic workflow to help you get started with Actions

name: WordPress Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ 5.6, 7.2 ]
        mysql: [ 5.6, 8.0 ]
        wordpress: [ 4.9, latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      -   name: Cache dependencies
          uses: actions/cache@v1
          with:
              path: ~/.composer/cache/files
              key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      
      # @link https://github.com/spatie/laravel-activitylog/blob/master/.github/workflows/run-tests.yml
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
            coverage: none
            
      - name: Set Up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.msql }}
          mysql user: 'root'
          mysql password: 'root'

      - name: Install dependencies
        run: |
          composer self-update --1
          composer require phpunit/phpunit:5.*
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Setup tests
        run: |
            bash tests/unit/bin/install.sh wordpress_test root root localhost ${{ matrix.wordpress }}

      -   name: Execute tests
          run: php -d memory_limit=-1 vendor/bin/phpunit
          env:
            DB_PORT: 3306
